spring:
  datasource:
    url: jdbc:postgresql://localhost:5444/books_manager_user_db
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  flyway:
    baseline-on-migrate: true
  jpa:
    hibernate:
      ddl-auto: update

jwt:
  secret-key: "78214125442A472D4B6150645367566B59703373367638792F423F4528482B4D"