CREATE TABLE IF NOT EXISTS _user (
    id BIGINT NOT NULL PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(255) NOT NULL,
    update_date TIMESTAMP NOT NULL,
    create_date TIMESTAMP NOT NULL
);